### ISSUE TITLE
documentation_error_pip

### ISSUE THREAD

**Issue by dan-ludwig-vroom** [tomasfarias/redtape#2]
In the documentation it says to install this library through pip by `python -m pip install redtape`, but at https://pypi.org/project/redtape-py/ it says you need to use `redtape-py` instead of just `redtape`. The redtape library is already taken.

**Comment by tomasfarias** [comment]
Fixed by latest commit: https://github.com/tomasfarias/redtape/commit/accb1b4a5ded6fb7022436a421de532911356dcc. Thanks for reporting this!
