### ISSUE TITLE
compare_user is a boolean when it shouldn't be

### ISSUE THREAD

**Issue by dan-ludwig-vroom** [tomasfarias/redtape#3]
In the admin.py file on line 256 `if compare_user := users_map.get(user.name, None) is not None:` compare_user becomes a boolean instead of a User object. Re-writing to this should fix it:

`compare_user = users_map.get(user.name)`
`if compare_user is not None:`
    `to_operate = user.member_of - compare_user.member_of`

**Comment by tomasfarias** [comment]
Thanks for reporting this!

Redtape needs a lot of work, but I don't really think there is anything out there yet. So I'll try to make a end of the year push and bring this to a more stable state.

**Comment by tomasfarias** [comment]
The first step will be to greatly extend our testing pipeline, as this could have been easily caught...
